### ISSUE TITLE
Uncaught (in promise)

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Athorcis/athorrent-client#23]
Error in console browser:
```
Uncaught (in promise) 
Object { request: {…}, status: 0, statusText: "", headers: {}, body: null, properties: {} }
​
body: null
​
headers: Object {  }
​
properties: Object {  }
​
request: Object { aborted: true, contentType: "application/json; charset=UTF-8", method: "GET", … }
​
status: 0
​
statusText: ""
​
<prototype>: Object { setProperty: setProperty(t, e), getProperty: getProperty(t), … }
```

**Comment by Athorcis** [comment]
Tu as rencontré l'erreur sur quelle page ? en faisant quoi exactement ?

**Comment by Jean-BaptisteC** [comment]
- Upload d'un torrent
- Aller sur Fichiers
- Retour sur Torrents
- Attendre -> au bout de 1 à 2 min les erreurs apparaissent dans la console
Dans l'onglet réseau, j'ai des requêtes GET en erreur (colonne transfert NS_BINDING_ABORTED)

**Comment by Athorcis** [comment]
Je n'ai pas réussi à reproduire le problème, mais si le problème n'apparait pas tout de suite il se peut que ce soit une requête qui prenne trop de temps et qui se fasse interrompre par la requête suivante, et ça ne semble pas vraiment entraver l'utilisation.
