### ISSUE TITLE
Errors doesn't used translations

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Athorcis/athorrent-client#30]
- Upload file not allowed --> Message: You can't upload files of this type.
- Upload file too big --> Message: File is too big (9.78MiB). Max filesize: 1MiB.

https://github.com/Athorcis/athorrent-frontend/blob/5e9dd6c563ed8e7663f66cd60030d484ce29881b/src/Controller/TorrentController.php#L75
https://github.com/Athorcis/athorrent-frontend/blob/5e9dd6c563ed8e7663f66cd60030d484ce29881b/src/Controller/TorrentController.php#L78

Server returns frameword errors, before he returns errors translation?

**Comment by Athorcis** [comment]
Well, not exactly, because if errors were returned before being translated, then you would have seen `error.fileTooBig` in the interface, instead you saw `File is too big (9.78MiB). Max filesize: 1MiB.`. However translation keys passed through Throwable weren't also translated 😅
