### ISSUE TITLE
Number of peers and seeds are negative

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Athorcis/athorrent-client#35]
How reproduce:
- Go to search
- Search James Bond
- Import last item of list
- Click on information button -> somes peers and seeds have a negative value

![image](https://github.com/Athorcis/athorrent-frontend/assets/87148630/e7ed60c3-4888-49b0-86c9-d6803ceb3e16)

As, I understand peer is one computer that has the file (or a part of the file) and is connected to the tracker.
I don't understand, how it's possible to know the number of peers if seedbox is not contacted to the tracker.
I think it's better to use `-` instead `-1` when value is unknow, wrong or negative.

**Comment by Athorcis** [comment]
That's exactly what means `-1`, that we don't know, but you're right I will switch to `-`
