### ISSUE TITLE
Check new password in local

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Athorcis/athorrent-client#37]
When you change your password, checks about the new password is done from the server side.
It's better to do it on the local side, to not show an error after refreshing the page and lose the passwords.
Two options:
- Add listener when user fills the confirmation password field
- Implement a check, when the user clicks on update button before the request was sent to the server

About check to verify if confirmation password is the same that new password, it's better to show warning on confirmation password not on new password

![image](https://github.com/Athorcis/athorrent-frontend/assets/87148630/02b1c5c0-30b2-49ff-90bd-29038558e977)

**Comment by Jean-BaptisteC** [comment]
I guess error is present in wrong field because we use `RepeatedType::class`

Another thing, it's seems this [translation](https://github.com/Athorcis/athorrent-frontend/blob/e8265d5a1031ffae5019a5095f092c35c58dcb58/translations/validators%2Bintl-icu.fr.yaml#L4) is not used

**Comment by Athorcis** [comment]
The form now use the correct translation (e42ceea12e521ff0e9bebef1127a68056667c7b1).
The choice of the field under which is visible the error is subjective so I won't change it for now.
About the js validation feel free to submit a PR
